export const currencyMap: Record<string, string> = {
  "€": "EUR",
  "$": "USD",
  "£": "GBP",
  "₽": "RUB",
  "¥": "JPY",
  "₩": "KRW",
  "₹": "INR",
  "₺": "TRY",
  "₴": "UAH",
  "฿": "THB",
  "₦": "NGN",
  "₲": "PYG",
  "₡": "CRC",
  "₱": "PHP",
  "₪": "ILS",
  "₵": "GHS",
  "₫": "VND",
  "₭": "LAK",
  "₸": "KZT",
  "₮": "MNT",
  "₧": "ESP",
  "₯": "GRD",
  "₠": "XEU",
  "ƒ": "ANG",
  "ден": "MKD",
  "ლ": "GEL",
  "сом": "KGS",
  "ман": "AZN",
  "руб": "RUB",
  "ريال": "SAR",
  "د.إ": "AED",
  "₿": "BTC"
};
  